name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          cd rock-paper-scissors-game
          curl -X POST "https://api.render.com/deploy/srv-YOUR_RENDER_SERVICE_ID?key=${RENDER_API_KEY}"
